FROM quay.io/redhat-appstudio-qe/build-e2e-hazk-tenant/build-suite-component-update-mcpa/multi-component-parent-rred@sha256:1ad9080aa4858d518e16dbe8ab730f6483cfa536945fa6c07e3d2f09742a56d8
RUN echo hello
