FROM quay.io/redhat-appstudio-qe/build-e2e-ekcz-tenant/build-suite-component-update-goko/multi-component-parent-wtvv@sha256:bd77b0c24a275c1979ae312cd78d9c66fc5d14437cb86b4cd57fb5e72b27057a
RUN echo hello
